version: '1'

services:
  db:
    image: 'mysql:5.7'
    platform: linux/amd64
    environment:
      - 'MYSQL_ROOT_PASSWORD=toor'
      - 'MYSQL_DATABASE=callActiv'
      - 'MYSQL_USER=callActiv'
      - 'MYSQL_PASSWORD=callActiv'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - dev

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - dev

  www:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    depends_on:
      - db
    ports:
      - '8080:80'
    volumes:
      - ./docker/web/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www:cached
      - ./docker/web/local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: always
    networks:
      - dev

  node:
    image: node:lts-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  db-data:
